[deploy_config]
chains = [
    "optimism_sepolia",
    "base_sepolia"
]
salt = "BTB_FINANCE_v1"  # This salt helps ensure same address across chains

[token]
name = "BTB Finance"
symbol = "BTB"
decimals = 18
owner_address = "0xBB29c2e6b6F2f3Bc12E6e6c54977fBb"  # Replace with your vanity address
